### ISSUE TITLE
Analyzing diploid mESC data from Nagano et al. (2017)

### ISSUE THREAD

**Issue by tarak77** [tanlongzhi/dip-c#2]
Hello @tanlongzhi ,

In Dip-C paper, there is a cross section view of the diploid interphase mESC cell 1CDX1-413 and some other cells. The model and its analysis looks good.
In the paper by Nagano et al. (2017) an intercross of Mus musculus 129/SV-Jae and Mus musculus castaneus cells were used. I had a big favor to ask- will it be possible to provide the source for the phased SNPs in VCF file for the mESC diploid cells? and an example pipeline used to generate the 3D models of these diploid mouse cells ? will definitely be great.

I really appreciate your help!

**Comment by tanlongzhi** [comment]
Thank you for your interest in the diploid mouse part of our Dip-C paper. This info is provided in the paper's supplement, and also edited and pasted below. The actual SNP file is large (~ 80 MB) and thus cannot be pasted here; if you really want it we can figure out a way of transferring.

<em>Source of Phased SNPs</em>
For mESCs, the parental lines were 129S4/SvJaeJ × Castaneus (Nagano et al. 2017). As an approximation, 129S1/SvImJ and CAST/EiJ were extracted from a dbSNP VCF file (the file `mgp.v5.merged.snps_all.dbSNP142.vcf.gz` from the Sanger Institute Mouse Genomes Project), yielding 21.50 million sites that were different between the two strains. I didn't filter out non-PASS SNPs.

<em>Special Considerations for Running Dip-C on Diploid mESCs</em>
In general, the smaller total numbers of contacts in these cells (compared to the Dip-C method) requires lowering the pipeline's stringency. In Table S1, relevant parameters were `dip clean -c1`, `dip-c impute -C1`, and `dip -c impute3 -C1`. In addition, more 3D modeling replicates (five) should be generated, because the smaller numbers of contacts and limited chromosome intermingling (a sentiment shared by the README of nuc_dynamics that inter-chromosomal contacts are more informative for 3D modeling) occasionally led to suboptimal structures. These suboptimal structures satisfied fewer contacts than other replicates, and were thus excluded. Typical median r.m.s. deviation was ~ 1.3 particle radii (~ 130 nm).

<em>Processed Data</em>
All final and intermediate files are available in the [GEO database](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE117109).

Best wishes for your diploid analysis!

**Comment by tarak77** [comment]
Hi @tanlongzhi, I did try to use `ftp://ftp-mouse.sanger.ac.uk/current_snps ` to get the vcf file for the hybrid mouse mentioned in the aper(Nagano et al. 2017) but for some reason the .vcf file looks corrupted and could not be used! Is there there a way to include that in the GEO database? so that I could access it?

**Comment by tanlongzhi** [comment]
Please use this temporary Dropbox [link](https://www.dropbox.com/s/ku8hajtdymhxpoz/cast_129.chr.txt.gz?dl=0) for the SNP file. The file begins with:
```
chr1	3000126	G	T
chr1	3000258	T	G
chr1	3001579	A	T
chr1	3003561	C	T
chr1	3005006	A	G
chr1	3007334	G	T
chr1	3007431	A	G
chr1	3007757	G	A
chr1	3007852	T	A
chr1	3007889	A	G
```

**Comment by wbszhu** [comment]
Hi @tanlongzhi，
The temporary Dropbox link for the SNP file is no longer available. Could you please give it again?

**Comment by tanlongzhi** [comment]
Hi @wbszhu, sorry about the expired link. You can find SNP files on my recent [GEO accession](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE146397):
1. [CAST (female) x B6 (male)](https://ftp.ncbi.nlm.nih.gov/geo/series/GSE146nnn/GSE146397/suppl/GSE146397_genomic_data.cast_b6.chr.txt.gz)
2. [B6 (female) x CAST (male)](https://ftp.ncbi.nlm.nih.gov/geo/series/GSE146nnn/GSE146397/suppl/GSE146397_genomic_data.b6_cast.chr.txt.gz)

**Comment by wbszhu** [comment]
Thanks a lot ~
