### ISSUE TITLE
Just thinking out loud

### ISSUE THREAD

**Issue by tarak77** [tanlongzhi/dip-c#22]
Hey @tanlongzhi ,
At present the pipeline requires the SNP VCF files to be given, but i was just curious whether using googles DeepVariant (a deep learning model for finding the variants) be useful or even help us find more phased legs?? 
I was thinking of implementing it. Let me know it makes sense to use it..

**Comment by tanlongzhi** [comment]
Hey @tarak77,

If you're talking about generating a phased SNP file from Dip-C data (instead of requiring a phased SNP file from external sources), yes I believe that's possible given a certain number of single cells. I'm thinking about implementing this in the future, but currently busy with a different project.

In bulk Hi-C, I think the first paper on this topic is [Selvaraj et al. 2013](https://www.nature.com/articles/nbt.2728); a more recent paper is [Edge et al. 2016](https://genome.cshlp.org/content/27/5/801).

If you're talking about increasing the percentage of phased leg given a phased SNP file, I don't think much improvement can be made, because this percentage is determined simply by how much the mother differs from the father.
