### ISSUE TITLE
Key difference between single cell hic and normal population hic in terms of building 3D model 

### ISSUE THREAD

**Issue by kainblue** [tanlongzhi/dip-c#29]
Hi Longzhi,

I really appreciate all the help you provide. I really like the 3D model you build in the original science paper. Now the biggest question in my mind is can I apply dip-c software on normal population hic? If not, what would be the key hurdle for preventing that happen?

Thanks

Bo

**Comment by tanlongzhi** [comment]
Hi Bo,

Please see my explanation in [this thread](https://github.com/lh3/hickit/issues/3#issuecomment-449766642).

In general, it's much easier to 3D-model single-cell data, because only a single 3D structure exists. However, there're already many papers on 3D-modeling bulk data. Two researchers I personally know are [Irene Farabella](https://scholar.google.co.uk/citations?user=Njnv1hgAAAAJ&hl=en) and [Bin Zhang](https://zhanggroup.mit.edu/); but there're plenty more working on bulk Hi-C.

**Comment by kainblue** [comment]
Thank you so much for pointing me to the right direction! I will look into the their work!

Bo
