### ISSUE TITLE
Error in converting .3dg from GEO database to .cif file for visualization in pymol 

### ISSUE THREAD

**Issue by tarak77** [tanlongzhi/dip-c#3]
Hi @tanlongzhi ,

I was also trying to visualize the mouse diploid genome using the output _.impute3.round4.clean.3dg files from the GEO database for 1CDX1-413 diploid cell by using the following command:

`(py2) Taraks-MacBook-Pro:dip-c tarakshisode$ ./dip-c color -n ./NXT-43.250kb/mm9.chr.txt ./CDX1-413.20k/CDX1-413.20k.dip-c.3dg | dip-c vis -c /dev/stdin ./CDX1-413.20k/CDX1-413.20k.dip-c.3dg > ./CDX1-413.20k/CDX1-413.20k.dip-c.cif`

Note that I am using mm9.chr.txt with chr1 through chrX 

I get the following error:
```
.
.
[M::color] analyzed 236000 particles (97.85%)
[M::color] analyzed 237000 particles (98.27%)
[M::color] analyzed 238000 particles (98.68%)
[M::color] analyzed 239000 particles (99.1%)
[M::color] analyzed 240000 particles (99.51%)
[M::color] analyzed 241000 particles (99.92%)
[M::color] writing 241181 colors (100.0%)
Traceback (most recent call last):
  File "./dip-c", line 122, in <module>
    main()
  File "./dip-c", line 73, in main
    return_value = color.color(sys.argv[1:])
  File "/Users/tarakshisode/dip-c/color.py", line 246, in color
    sys.stdout.write("\t".join([hom_name, str(ref_locus), str(color_data[(hom_name, ref_locus)])]) + "\n")
IOError: [Errno 32] Broken pipe
```

Any help will be great!

**Comment by tanlongzhi** [comment]
I think this may be caused by your typo of `| dip-c vis` (should be `| ./dip-c vis`). I just ran the same code on that cell (`GSE117109_GSM2476407_1CDX1-413.impute3.round4.clean.3dg`) and obtained the following screenshot:
<img width="972" alt="diploid_mouse pymol" src="https://user-images.githubusercontent.com/2436999/45187690-93d84080-b1ff-11e8-9489-a4a593e1b46c.png">

The script below was used for styling in PyMol:
```python
as sticks, all
set_bond stick_radius, 0.5, all
spectrum b, rainbow, all, 1, 20
```

**Comment by tarak77** [comment]
Got it! Thank you very much
