### ISSUE TITLE
Doubt in Haplotype imputation(2D) from supplementary material

### ISSUE THREAD

**Issue by tarak77** [tanlongzhi/dip-c#4]
Hi Tan,
I was going over haplotype imputation step(2D) from the supplementary material and was a bit unclear with the figure S7E. Missing haplotype of a given contact could be imputed from haplotypes of other contacts in its superelliptical neighborhood. And this is based on a voting system. What exactly does n in the same figure represent? And why for n=90 it is uninformative? 

Again, intrachromosomal contacts that had unknown haplotypes on both legs were not imputed but inter chromosomal were?

**Comment by tanlongzhi** [comment]
Thank you Tarak for the question. In Fig. S7E, *n* denotes the number of red dots (contacts) in the red-shaded region (superelliptical neighborhood). Most contacts are uninformative because ~ 90% of all contacts carry no haplotypo info (didn't overlap with any phased SNPs)

You're correct about intrachromosomal contacts in the initial (2D) imputation. This is to account for the higher imputation uncertainty for intrachromosomal contacts. In this repo, their imputation is left for subsequent imputation (3D).

In @lh3's more careful implementation in hickit, however, imputation uncertainty for intrachromosomal contacts is quantified and directly taken into account during the voting procedure.

**Comment by tarak77** [comment]
And why is there a higher imputation uncertainty for intrachromosomal contacts?

**Comment by tanlongzhi** [comment]
Imputation relies on the assumption that the two homologs have different contacts (see the main text). This assumption get poorer when a contact is closer to the diagonal.

For example, when we see a contact far away from the diagonal, for example between positions 10 Mb and 200 Mb on chromosome 1, we can safely assume that this very long-range loop is only occurring on *one* of the two homologs, and therefore can be imputed confidently.

However, when we see a contact close to the diagonal, for example between positions 10 Mb and 10.1 Mb on chromosome 1, it's entirely possible that this short-range loop is occurring on *both* homologs (because chromosomes are basically polymer rods with lots of short-range contacts), and therefore should not be imputed (assigned to one homolog).

**Comment by tarak77** [comment]
I see now, so these short range contacts are assigned to both homologs? 
Also you mention that the imputation procedure begins with all contacts that had known haplotypes on at least one leg, then results were subsequently cleaned by removal of isolated contacts. Could you explain why you have defined these isolated contacts like in the supplementary material?
Lastly, and how the cleaned results were used as the evidence set to impute a target set of all interchromosomal contacts that had unknown haplotypes on both legs?

**Comment by tanlongzhi** [comment]
In fact I assigned these short-range contacts to *neither*, given the uncertainty. There is, however, a [previous paper](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005292) (studying intrachromosomal contacts, exclusively) chose a strategy more like *either* or *both*.

**Comment by tarak77** [comment]
I get it now, thanks!

**Comment by tanlongzhi** [comment]
Regarding your other questions:

- I took the definition of isolated contacts mostly from Stevens et al. (2017). The only (minor) difference is that they used a rectangular neighborhood while I used a superelliptical one. It seems, at least in my hands, that the 3C assay generates a uniform background of artifactual contacts randomly across the genome. These add a small noise to imputation and thus have to be taken into account.

- In 2D imputation, after the first round, many interchromosomal contacts with SNPs on one leg will have both legs phased. In subsequent rounds, these contacts will then vote for the remaining contacts as if these contacts already have haplotypes on both legs.
